### ISSUE TITLE
Feature: Allow failed build artifacts to be kept longer than successful ones

### ISSUE THREAD

**Issue by JacquesOfAllTrades** [jenkinsci/build-discarder-plugin#53]
### What feature do you want to see added?

There are classic plugins for this feature, but none of those are compatible with pipelines as far as I know. If there is an existing, *pipeline-compatible* plugin or other method to achieve this, please let me know!

Justification:

Because I'm trying to push our organization towards pipelines for all of our jobs, this missing feature is problematic. We have dozens of jobs, and some of them generate sizable artifacts that we don't want to keep for successful builds (except for the last 1 or 2). On the other hand, if a failure occurs when nobody is available to review it, we need to ensure that it cannot be discarded due to new, successful builds.

This likely isn't a problem for anyone whose tests are very granular and deterministic, because their tests will either consistently succeed or consistently fail. However, *that's not our use case*, and I'm sure we're not the only ones. Many of our tests are very complex, system-level tests that use networking and multi-threading, so it's not uncommon to encounter intermittent failures due to variations in network conditions and timing.

Proposed operation:

Given that these are the currently supported parameters:
```
            artifactDaysToKeepStr: "50"
            artifactNumToKeepStr: "5"
            daysToKeepStr: "100"
            numToKeepStr: "10"
```
I believe the simplest approach would be to create one more:
```
            failedArtifactMinimumNumToKeepStr: "2" // Value for illustration, not default
```
Assuming that `artifactNumToKeepStr` should continue to dictate the absolute maximum number of jobs' artifacts to keep, the above numbers would be interpreted to mean keeping artifacts for up to 1 failure and up to 5 total jobs, regardless of the specific breakdown. That is, keep 5 successful, or 1 failed and 4 successful, or 2 failed and 3 successful. `artifactDaysToKeepStr` would continue to be enforced for all jobs like it currently is.

I wish I had time to submit a proposed implementation, but my company's software team is too understaffed for that. :(

Thanks for your consideration.

**Comment by orjan** [comment]
The main goal for this plugin is to provide a default that can be overridden by specifying a discarder for the job it self. I don't thing there's a way to configure this for a specific job? So if we're going to add this we'll need to extend the plugin so we can have a different retention policy for failed jobs.

I think this is a corner case for this plugin and I'm not sure if it should be part of this plugin?

I would probably look into saving or tagging the build on failure instead of changing the global settings? Where you can tag failed build with or save the artefact where you having a different retention policy?
<img width="190" alt="image" src="https://user-images.githubusercontent.com/124032/162627218-14f5aedd-c7ed-4733-bb05-ca0191a0ace2.png">


```
pipeline {
    agent any
    stages {
        ...
    }
    post {
        failure {
            echo 'I failed :('
        }
    }
}
```

**Comment by JacquesOfAllTrades** [comment]
Thank you for your response.

You're right--I didn't submit this to the appropriate project. Sorry about that! I will close it.

Thanks also for the suggestions. The solution I'm looking for can't require user action, because the idea is to preserve troubleshooting data when the responsible user isn't available right away (due to a weekend, or vacation, etc.). Most of our jobs haven't yet been converted to pipeline, but it seems that the extra control pipeline scripts provide may allow us to do what we need. I will look into this.

Best regards!
