### ISSUE TITLE
Global Build Discarders overrides Pipeline Discard old builds

### ISSUE THREAD

**Issue by jfranzoi-gucci** [jenkinsci/build-discarder-plugin#87]
Hello, sorry for this basic question, I was looking on the web but found no similar issue.

Given a Global Build Discarders configuration (eg: keep last 5 builds) and some pipeline specific ones (eg: keep last 20 ones), I'd expect the default to be applied only on those pipelines lacking any log build discarder configuration. What I'm seeing instead, is the default one always being applied, no matter what I configure at pipeline level.

Is there any error in my configuration? Here it is, for reference:

**Global Build Discarders**
1. Project Build Discarder (no additional options)
2. Specific Build Discarder (`strategy: Log Rotation, Max # of builds to keep: 5`)

**Pipeline**
- Discard old builds: (`strategy: Log Rotation, Max # of builds to keep: 20`) 

![global](https://user-images.githubusercontent.com/93207984/182312825-e14b1e79-21dc-409a-b124-99d26f89bca6.png)
![pipeline](https://user-images.githubusercontent.com/93207984/182312922-3f1285e8-6adf-4a78-bbac-c534cbadff3c.png)

Thanks in advance,
regards.

- Jenkins version: `2.346.2`
- Build Discarder version: `60.v1747b0eb632a`

**Comment by orjan** [comment]
@jfranzoi-gucci it looks like you're a using the built in discarder and not the one from the plugin, if you're looking at this image, https://github.com/jenkinsci/build-discarder-plugin#getting-started?

Isn't there an option where you can select the "Default Build Discarder"?

**Comment by orjan** [comment]
@jfranzoi-gucci I'm closing it for now, feel free to open it again if it's not working once you have change the `Specific Build Discarder` to `Default Build Discarder`
